export const columnDefs = [
    {
        headerName: 'Name', 
        field: 'name',
        sortable: true,
        filter: true,
    }, 
    {
        headerName: 'Base', 
        field: 'base',
        sortable: true,
        filter: true,
    }, 
    {
        headerName: 'Quote', 
        field: 'quote',
        sortable: true,
        filter: true,
    },
    {
        headerName: 'Fee_ask', 
        field: 'fee_ask',
        sortable: true,
        filter: true,
    },
    {
        headerName: 'Fee_bid', 
        field: 'fee_bid',
        sortable: true,
        filter: true,
    },
    {
        headerName: 'Disabled', 
        field: 'disabled',
        sortable: true,
        filter: true,
        width: 175,
    },
    {
        headerName: 'Test_mode', 
        field: 'test_mode',
        sortable: true,
        filter: true,
        width: 175,
    },
    {
        headerName: 'Orderbook_enabled', 
        field: 'orderbook_enabled',
        sortable: true,
        filter: true,
        width: 175,
    },
    {
        headerName: 'Reverse_orderbook_enabled', 
        field: 'reverse_orderbook_enabled',
        sortable: true,
        filter: true,
        width: 175,
    },
]